defaults:
  - default.yaml

train:
  dataset:
    _target_: medvae.dataloaders.ConcatDataset
    datasets:
      #OASIS
      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/oasis.csv
        split_column: split
        split_name: train
        data_dir: ${paths.data_dir}/oasis/
        dataset_id: 0
        img_column: image_uuid
        img_suffix: .npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: medvae.utils.loaders.load_oasis
              return_2_ch: true

      # complex data
      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/bruno.csv
        split_column: split
        split_name: train
        data_dir: ${paths.data_dir}/bruno/
        dataset_id: 0
        img_column: image_uuid
        img_suffix: .npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: medvae.utils.loaders.load_bruno

      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/bruno_dicoms.csv
        split_column: split
        split_name: train
        data_dir: ${paths.data_dir}/bruno_dicoms/
        dataset_id: 0
        img_column: image_uuid
        img_suffix: .npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: medvae.utils.loaders.load_bruno_dicoms
              return_2_ch: true

valid:
  dataset:
    _target_: medvae.dataloaders.ConcatDataset
    datasets:
      # OASIS
      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/oasis.csv
        split_column: split
        split_name: val
        data_dir: ${paths.data_dir}/oasis/
        dataset_id: 0
        img_column: image_uuid
        img_suffix: .npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: medvae.utils.loaders.load_oasis
              return_2_ch: true

      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/bruno.csv
        split_column: split
        split_name: val
        data_dir: ${paths.data_dir}/bruno/
        dataset_id: 0
        img_column: image_uuid
        img_suffix: .npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: medvae.utils.loaders.load_bruno

      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/bruno_dicoms.csv
        split_column: split
        split_name: val
        data_dir: ${paths.data_dir}/bruno_dicoms/
        dataset_id: 0
        img_column: image_uuid
        img_suffix: .npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: medvae.utils.loaders.load_bruno_dicoms
              return_2_ch: true

test:
  dataset:
    _target_: medvae.dataloaders.ConcatDataset
    datasets:
      # OASIS
      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/oasis.csv
        split_column: split
        split_name: test
        data_dir: ${paths.data_dir}/oasis/
        dataset_id: 0
        img_column: image_uuid
        img_suffix: .npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: medvae.utils.loaders.load_oasis
              return_2_ch: true
  
      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/bruno.csv
        split_column: split
        split_name: test
        data_dir: ${paths.data_dir}/bruno/
        dataset_id: 0
        img_column: image_uuid
        img_suffix: .npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: medvae.utils.loaders.load_bruno

      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/bruno_dicoms.csv
        split_column: split
        split_name: test
        data_dir: ${paths.data_dir}/bruno_dicoms/
        dataset_id: 0
        img_column: image_uuid
        img_suffix: .npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: medvae.utils.loaders.load_bruno_dicoms
              return_2_ch: true